# Generated by Django 4.0.4 on 2022-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0003_alter_player_image_alter_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='images/default_profile_picture.png', upload_to='images/players/'),
        ),
    ]
