# Generated by Django 4.0.4 on 2022-05-19 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0004_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='images/default_profile_picture.jpg', upload_to='images/players/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
