# Generated by Django 4.0.4 on 2022-05-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0006_player_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.player')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Football.message')),
                ('invited_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.team')),
            ],
            bases=('Football.message',),
        ),
    ]
