# Generated by Django 4.0.4 on 2022-05-25 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0008_message_sender_alter_message_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Football.message')),
                ('date', models.DateTimeField()),
                ('challenged_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.team')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.stadium')),
            ],
            bases=('Football.message',),
        ),
    ]
