# Generated by Django 4.0.4 on 2022-05-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0009_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Football.message')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Football.match')),
            ],
            bases=('Football.message',),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenging_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='challenging_team', to='Football.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Football.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenged_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenged_team', to='Football.team'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='player',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Asist',
        ),
    ]
