# Generated by Django 4.0.4 on 2022-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0011_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.DateField(),
        ),
    ]
