# Generated by Django 4.0.4 on 2022-05-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0014_alter_challenge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
