# Generated by Django 4.0.4 on 2022-05-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football', '0016_postscore_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
